version: 1
indices:
  default:
    include:
      - /**
    exclude:
      - /drafts/**
      - /tools/sidekick/**
      - /fragments/**
      - /library/**
      - /modals/**
      - /blogs/**
    target: /query-index.json
    properties:
      title:
        select: head > meta[property="og:title"]
        value: |
          attribute(el, 'content')
      description:
        select: head > meta[name="description"]
        value: |
          attribute(el, 'content')
      image:
        select: head > meta[property="og:image"]
        value: |
          match(attribute(el, 'content'), "https:\/\/[^/]+(/.*)")
      lastModified:
        select: none
        value: >
          parseTimestamp(headers["last-modified"], "ddd, DD MMM YYYY hh:mm:ss
          GMT")
      robots:
        select: head > meta[name="robots"]
        value: |
          attribute(el, 'content')
  blog:
    include:
      - /blog/**
    exclude:
      - /drafts/**
      - /tools/sidekick/**
      - /fragments/**
      - /library/**
      - /modals/**
    target: /blog-index.json
    properties:
      title:
        select: head > meta[property="og:title"]
        value: |
          attribute(el, 'content')
      description:
        select: head > meta[name="description"]
        value: |
          attribute(el, 'content')
      image:
        select: head > meta[property="og:image"]
        value: |
          match(attribute(el, 'content'), "https:\/\/[^/]+(/.*)")
      tags:
        select: head > meta[property="article:tag"]
        values: |
          attribute(el, 'content')
      date:
        select: head > meta[name="date"]
        value: |
          parseTimestamp(attribute(el, 'content'), 'MM/DD/YYYY')
      author:
        select: head > meta[name="author"]
        value: |
          attribute(el, 'content')
      lastModified:
        select: none
        value: >
          parseTimestamp(headers["last-modified"], "ddd, DD MMM YYYY hh:mm:ss
          GMT")
      robots:
        select: head > meta[name="robots"]
        value: |
          attribute(el, 'content')
